mutation GetOrCreateGameLog($input: GetOrCreateGameLogInput!) {
	getOrCreateGameLog(input: $input) {
		... on GameLog {
			id
			title
			brief
			synopsis
			gameDate
			url
		}
		... on OperationInfo {
			messages {
				field
				kind
				message
			}
		}
	}
}
