mutation UnlockCharacterEditor($id: ID!) {
	unlock(input: { id: $id }) {
		__typename
		... on Character {
			id
			name
			description
			markdownNotes
			size
			imageIds
			lockedBySelf
			lockUser {
				id
				username
				firstName
				lastName
			}
			race {
				id
				name
			}
			associations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedArtifacts {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedAssociations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedCharacters {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedItems {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedPlaces {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedRaces {
				edges {
					node {
						id
						name
					}
				}
			}
			logs(order: { gameDate: DESC }) {
				edges {
					node {
						id
						title
						url
					}
				}
			}
		}
	}
}
