mutation UpdateCharacterEditor(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$size: String
	$race: NodeInput
	$associations: [NodeInput!]
	$relatedArtifacts: [NodeInput!]
	$relatedAssociations: [NodeInput!]
	$relatedCharacters: [NodeInput!]
	$relatedItems: [NodeInput!]
	$relatedPlaces: [NodeInput!]
	$relatedRaces: [NodeInput!]
) {
	updateCharacter(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			size: $size
			race: $race
			associations: { set: $associations }
			relatedArtifacts: { set: $relatedArtifacts }
			relatedAssociations: { set: $relatedAssociations }
			relatedCharacters: { set: $relatedCharacters }
			relatedItems: { set: $relatedItems }
			relatedPlaces: { set: $relatedPlaces }
			relatedRaces: { set: $relatedRaces }
		}
	) {
		__typename
		... on Character {
			id
			name
			description
			markdownNotes
			size
			imageIds
			lockedBySelf
			lockUser {
				id
				username
				firstName
				lastName
			}
			race {
				id
				name
			}
			associations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedArtifacts {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedAssociations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedCharacters {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedItems {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedPlaces {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedRaces {
				edges {
					node {
						id
						name
					}
				}
			}
			logs(order: { gameDate: DESC }) {
				edges {
					node {
						id
						title
						url
					}
				}
			}
		}
		... on OperationInfo {
			messages {
				code
				field
				kind
				message
			}
		}
	}
}
