query ItemDetail($id: ID!) {
	node(id: $id) {
		... on Item {
			id
			name
			description
			markdownNotes
			imageIds
			armor {
				acBonus
			}
			weapon {
				attackBonus
			}
			equipment {
				briefDescription
			}
			relatedArtifacts {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedAssociations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedCharacters {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedItems {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedPlaces {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedRaces {
				edges {
					node {
						id
						name
					}
				}
			}
			logs {
				edges {
					node {
						id
						title
						url
					}
				}
			}
		}
	}
}
