query PlaceDetail($id: ID!) {
	node(id: $id) {
		... on Place {
			id
			name
			description
			markdownNotes
			placeType
			parent {
				id
				name
				parent {
					id
					name
					parent {
						id
						name
						parent {
							id
							name
							parent {
								id
								name
								parent {
									id
									name
								}
							}
						}
					}
				}
			}
			children {
				edges {
					node {
						id
						name
					}
				}
			}
			imageIds
			relatedArtifacts {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedAssociations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedCharacters {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedItems {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedPlaces {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedRaces {
				edges {
					node {
						id
						name
					}
				}
			}
			logs(order: { gameDate: DESC }) {
				edges {
					node {
						id
						title
						url
					}
				}
			}
		}
	}
}
