mutation UpdatePlaceEditor(
	$id: ID!
	$name: String
	$description: String
	$markdownNotes: String
	$placeType: PlaceType
	$parent: NodeInput
	$relatedArtifacts: [NodeInput!]
	$relatedAssociations: [NodeInput!]
	$relatedCharacters: [NodeInput!]
	$relatedItems: [NodeInput!]
	$relatedPlaces: [NodeInput!]
	$relatedRaces: [NodeInput!]
) {
	updatePlace(
		input: {
			id: $id
			name: $name
			description: $description
			markdownNotes: $markdownNotes
			placeType: $placeType
			parent: $parent
			relatedArtifacts: { set: $relatedArtifacts }
			relatedAssociations: { set: $relatedAssociations }
			relatedCharacters: { set: $relatedCharacters }
			relatedItems: { set: $relatedItems }
			relatedPlaces: { set: $relatedPlaces }
			relatedRaces: { set: $relatedRaces }
		}
	) {
		__typename
		... on Place {
			id
			name
			description
			markdownNotes
			placeType
			imageIds
			lockedBySelf
			lockUser {
				id
				username
				firstName
				lastName
			}
			parent {
				id
				name
				parent {
					id
					name
					parent {
						id
						name
						parent {
							id
							name
							parent {
								id
								name
								parent {
									id
									name
								}
							}
						}
					}
				}
			}
			children {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedArtifacts {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedAssociations {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedCharacters {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedItems {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedPlaces {
				edges {
					node {
						id
						name
					}
				}
			}
			relatedRaces {
				edges {
					node {
						id
						name
					}
				}
			}
			logs(order: { gameDate: DESC }) {
				edges {
					node {
						id
						title
						url
					}
				}
			}
		}
		... on OperationInfo {
			messages {
				code
				field
				kind
				message
			}
		}
	}
}
